blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/ACT-Training/query-builder/discussions/new?category=q-a
    about: Ask the community for help
  - name: Report a security issue
    url: https://github.com/ACT-Training/query-builder/security/policy
    about: Learn how to notify us for sensitive bugs
